<?php
    echo('----------<br>');
    echo('사과<br>');
    echo('오렌지<br>');
    echo('----------<br>');
    echo('&^%$#!@%!#&^&(<br>');
    echo('----------<br>');
    echo('사과<br>');
    echo('오렌지<br>');
?>